In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

%matplotlib inline
# import mpld3

In [112]:
df = pd.DataFrame.from_csv('Crimes_-_2001_to_present.csv', infer_datetime_format=True)

In [113]:
df

                            Date         Primary Type
ID
10028048  04/10/2015 11:45:00 PM              BATTERY
10028038  04/10/2015 11:40:00 PM              BATTERY
10028104  04/10/2015 11:38:00 PM              ASSAULT
10028046  04/10/2015 11:35:00 PM              ASSAULT
10028704  04/10/2015 11:30:00 PM              ASSAULT
21814     04/10/2015 11:16:00 PM             HOMICIDE
10028822  04/10/2015 11:05:00 PM              BATTERY
10028083  04/10/2015 11:00:00 PM              BATTERY
10028022  04/10/2015 11:00:00 PM              BATTERY
10028059  04/10/2015 11:00:00 PM              BATTERY
10028068  04/10/2015 10:52:00 PM              BATTERY
10028017  04/10/2015 10:45:00 PM              BATTERY
10027991  04/10/2015 10:36:00 PM              BATTERY
10028005  04/10/2015 10:36:00 PM              BATTERY
10028003  04/10/2015 10:35:00 PM              BATTERY
10028243  04/10/2015 10:30:00 PM              BATTERY
10028004  04/10/2015 10:30:00 PM              BATTERY
10031656  04/10/2015 10:30:00 PM              ASSAULT
10028014  04/10/2015 10:20:00 PM              ROBBERY
10028027  04/10/2015 10:11:00 PM              BATTERY
10028015  04/10/2015 10:10:00 PM              BATTERY
10027968  04/10/2015 10:03:00 PM              BATTERY
10028007  04/10/2015 10:02:00 PM              BATTERY
10028499  04/10/2015 10:00:00 PM              BATTERY
10033702  04/10/2015 10:00:00 PM              BATTERY
10028071  04/10/2015 09:50:00 PM              BATTERY
10027972  04/10/2015 09:48:00 PM              ASSAULT
10028052  04/10/2015 09:45:00 PM              BATTERY
10027930  04/10/2015 09:34:00 PM              BATTERY
10028012  04/10/2015 09:33:00 PM              BATTERY
...                          ...                  ...
1310025   01/01/2001 12:20:00 AM              BATTERY
1917213   01/01/2001 12:15:00 AM              BATTERY
1310092   01/01/2001 12:10:00 AM              BATTERY
1310686   01/01/2001 12:05:00 AM              BATTERY
1311915   01/01/2001 12:05:00 AM              BATTERY
7602291   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
5799746   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
5190122   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
1800761   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
3826855   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
1376172   01/01/2001 12:01:00 AM              BATTERY
4892881   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
2307556   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
4486858   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
8623828   01/01/2001 12:01:00 AM  CRIM SEXUAL ASSAULT
3496126   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
6483603   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
3994567   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
1448953   01/01/2001 12:00:00 AM              ASSAULT
8197725   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
6884455   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
8146039   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
9652075   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
5508664   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
2743135   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
5785840   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
9442043   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
2126730   01/01/2001 12:00:00 AM  CRIM SEXUAL ASSAULT
1310541   01/01/2001 12:00:00 AM              BATTERY
1362018   01/01/2001 12:00:00 AM              ASSAULT

[1648941 rows x 2 columns]

In [114]:
df['Primary Type'].value_counts()

BATTERY                1051897
ASSAULT                 349712
ROBBERY                 215895
CRIM SEXUAL ASSAULT      20980
HOMICIDE                  7042
INTIMIDATION              3414
DOMESTIC VIOLENCE            1
dtype: int64

In [115]:
violent_crimes = df.convert_objects(convert_numeric=True)
violent_crimes['Date'] = pd.to_datetime(violent_crimes['Date'])

### have datetime column with m/d/y and want to show the cumulative count across all the years for each m/d

In [109]:
sexual_assault = violent_crimes[(violent_crimes['Primary Type'] == 'CRIM SEXUAL ASSAULT')]

# sexual_assault['Date'] = pd.DatetimeIndex(sexual_assault['Date'])

dates = pd.DatetimeIndex(sexual_assault['Date'])
counts = sexual_assault.groupby(dates.month).cumsum()

# errors = sexual_assault.groupby(dates.month).std()
# ax=sexual_assault.groupby(dates.day).cumsum().plot(yerr=errors, kind='bar')
# ax.set_xlabel("months")
# ax.set_ylabel("gross")

In [ ]:
violent_crimes.set_index('Date')
violent_crimes